name: backend-image

on:
  push:
    branches: [main]
    paths:
      - "saas-platform/backend/**"

jobs:
  push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: saas-platform/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/saas-backend" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        run: docker build -t $IMAGE_NAME:latest .

      - name: Push
        run: docker push $IMAGE_NAME:latest